---
title: "training dataset CHETAH"
output: html_document
---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(SingleCellExperiment)
load("CHETAH_TME_reference.Rdata")
```

```{r}
reference
```

```{r}
logcounts(reference) <- counts(reference)
reference
```

```{r}
seurat <- as.Seurat(reference)
seurat
```

```{r}
seurat <- seurat %>% 
  FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
  ScaleData() %>% 
  RunPCA(npcs = 50) %>%
  RunUMAP(dims = 1:30, a = .5, b = 1.2) %>%
  FindNeighbors(dims = 1:30) %>% 
  FindClusters(resolution = 1.2)
```

```{r fig.height=5, fig.width=10}
#Idents(seurat) <- seurat$seurat_clusters
DimPlot(seurat, label = TRUE)
DimPlot(seurat, group.by = c("seurat_clusters", "celltypes"), label = TRUE) + NoLegend()
```

```{r fig.height=12, fig.width=12}
markers <- readxl::read_excel("TME_markerGenes.xlsx")
DotPlot(seurat, features = unique(markers$gene), cluster.idents = TRUE) + coord_flip() + NoLegend()
```

```{r}
anno_clust <- readxl::read_excel("annotation_CHETAH.xlsx")
anno_clust <- arrange(anno_clust, seurat_clusters)
new.cluster.ids <- tolower(anno_clust$abbreviation)
names(new.cluster.ids) <- levels(seurat)
seurat <- RenameIdents(seurat, new.cluster.ids)
seurat$abbreviation <- Idents(seurat)
cell_ont <- readxl::read_excel("cell_ontology.xlsx")
cell_ont$abbreviation <- tolower(cell_ont$abbreviation)
seurat@meta.data <- seurat@meta.data %>%
  tibble::rownames_to_column("cell") %>%
  left_join(cell_ont, by = "abbreviation") %>%
  tibble::column_to_rownames("cell")
Idents(seurat) <- seurat$cell_ontology
```

```{r}
seurat <- seurat[, !grepl("doublets", seurat@meta.data$abbreviation)]
seurat$celltypes <- seurat$cell_ontology
seurat
```

```{r}
DimPlot(seurat, label = TRUE)
```

```{r}
reference <- as.SingleCellExperiment(seurat)
reference
```

```{r}
save(reference, file = "CHETAH_reference_updatedAnnotation.RData")
```

